### PR TITLE
Update controller add-ons and add Genesis controllers

### PR DESCRIPTION
**Pull request by garbear**
## Description

This PR adds the new Genesis controllers added by @KOPRajs and updates the language strings of the rest of the controller add-ons.

~~However, updates to default, snes, keyboard and mouse are not included. Because these four add-ons ship to every new install, I'll wait until the next release to update these.~~

Newly added:

  * game.controller.genesis.3button - https://github.com/kodi-game/controller-topology-project/pull/203
  * game.controller.genesis.4wayplay - https://github.com/kodi-game/controller-topology-project/pull/215
  * game.controller.genesis.teamplayer - https://github.com/kodi-game/controller-topology-project/pull/206

~~Not to be merged before completing https://github.com/kodi-game/game.libretro/pull/105.~~

Also includes:

  * Added "Analog" buttons for PS Dualshock and PS Dual Analog controllers - https://github.com/kodi-game/controller-topology-project/pull/226

### CODE REVIEW

**Comment by KOPRajs** [comment]
> Not to be merged before completing [kodi-game/game.libretro#105](https://github.com/kodi-game/game.libretro/pull/105).

Why not? This doesn't depend on the change in _game.libretro_, does it?

**Comment by garbear** [comment]
It doesn't, I figured we'd get Genesis working fully in case we need to make an add-on change (though unlikely), and if we make a change I'll force push to this PR so we don't have to open multiple PRs against repo-resources.

We can merge this before https://github.com/kodi-game/game.libretro/pull/105 I just wanted a warning sign in case someone else came through with an itchy merge finger.

**Comment by garbear** [comment]
Updated to include https://github.com/kodi-game/controller-topology-project/pull/226 and recent translations

**Comment by garbear** [comment]
Updated again to include recent translations. I'll PR the controllers we ship to upstream `master` and `Nexus` in time for the v20.1 release, then we can merge this.

**Comment by garbear** [comment]
PRs have been open upstream:

* https://github.com/xbmc/xbmc/pull/22927
* https://github.com/xbmc/xbmc/pull/22928

When those have been merged, this PR can be merged.

**Comment by garbear** [comment]
xbmc repo PRs have been merged, this is ready to go

**Pull request merged**
