### PR TITLE
[resource.images.skinbackgrounds.metrocity] 1.0.0

### PR DESCRIPTION
**Pull request by dproudmoore**
### Description
Photographic style skin background images.

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] 1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Rechi** [comment]
> Each add-on submission should be a single commit with using the following style: [plugin.video.foo] 1.0.0

You have to open septate PRs for your add-ons.

**Comment by dproudmoore** [comment]
> > Each add-on submission should be a single commit with using the following style: [plugin.video.foo] 1.0.0
> 
> You have to open septate PRs for your add-ons.

Sorry, I didn't realise commits made after the PR got included in too.

**Comment by Rechi** [comment]
You introduced now another commit (the revert one).

**Comment by dproudmoore** [comment]
So how am I supposed to delete them?

**Comment by dproudmoore** [comment]
Thanks, I've done that now. I'll be sure to make better use of separate branches or something in the future.

**Comment by ronie** [comment]
thx!

**Pull request merged**
