### PR TITLE
Update from Transifex

### PR DESCRIPTION
**Pull request by ronie**
### Description

Update language files from Transifex (2020-11-20)

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by gade01** [comment]
Lines have been wrapped at 77 characters.
I know that Transifex does that by default. 
Do we have any issues with it since it has been corrected before?

Other than that, it looks really great.

**Comment by ronie** [comment]
not sure how easy it is to correct that, but i'll give it a shot.

other than that, i just realized it also needs a version bump in every addon.xml
so i'll work on that as well.

**Comment by gade01** [comment]
Weblate can probably fix the line wrapping once synced.
There's an addon for exactly that.

**Comment by ronie** [comment]
this is the best i can do.

the main diff is that untranslated strings are now also included in the language files.
```
msgctxt "#38074"
msgid "Boxsets"
msgstr ""
```
i can't find a way to exclude those.
it should not be a problem though.

**Comment by ronie** [comment]
ok, after dozens of forced pushes i'm happy now.

this is good to go as far as i'm concerned.

**Review by ksooo — APPROVED** [review]
Shove it in.

**Review by gade01 — APPROVED** [review]
Really nice work @ronie 

AFAIK Weblate will include untranslated strings as well.

**Comment by ronie** [comment]
let's hope we can make switch to weblate soon, cause it has been a pain to do it manually.

**Comment by ksooo** [comment]
Will due to this merge new versions of the language pack addons be available in our repo or is this another (manual) step?

**Comment by ronie** [comment]
@ksooo this is all that's needed.

**Pull request merged**
