### PR TITLE
[Jarvis] Run PNGcrush -ow -rem allb -reduce + Add Dutch studio images

### PR DESCRIPTION
**Pull request by mikesilvo164**
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**? 2 commits in case running PNGcrush is not desired ?**
I can squash if and/or rename commit to [resource.images.studios.coloured] v0.0.9 if preferred 😃 

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by ronie** [comment]
thx, i have no problem with the png optimization
the new dutch logos look a little stretched though....

**Comment by mikesilvo164** [comment]
@ronie 
I was afraid of something like that...

I was given these images from a user but I batched resized to 161x109 to match the others and that was a mistake.

I have not learned how to manipulate images yet. Here are the [original files](http://www.mediafire.com/file/vl73p7kwhcbpc1n/Dutch%20Studio%20Icons.zip).

Is there anyway you could take a look and maybe fix them or advise on how to use gimp to scale them correctly without distorting?

Thanks

**Comment by mikesilvo164** [comment]
@ronie Thanks 😃

I just couldn't get my head around it but now that you posted instructions about the canvas size I feel silly that I wasn't able to figure that out... I think it is correct now 🤞 

I updated the branch with the new images. Would you like me to do anything else?

Again my thanks for the instructions. Will help me a lot👍

**Comment by ronie** [comment]
than, they look great now!

**Pull request merged**
