### PR TITLE
[lang] minor corrections to match Transifex codes

### PR DESCRIPTION
**Pull request by alanwww1**
I am creating the database to match kodi language codes to future new Transifex codes and I realized, that there a 3 codes not available at all on Transifex:
fa_AF
os_OS
uz_UZ

I'd like to change them over so that I can use a matching Transifex code.
I think we can delete fa_AF completely as it is below 10% translated and not active.

os_OS and uz_UZ can be renamed to os and uz.

I hope these changes are still possible.
Any objections from @Montellese and @MartijnKaijser ?

### CODE REVIEW

**Comment by Montellese** [comment]
What will happen with people that had `Persian` set as their language? They will fall back to English.
The rest is fine with me but I don't really know the implications of having these language addons in our official repository.

**Comment by alanwww1** [comment]
They are more less having English anyway, because kodi core is translated only 8% while
Persian (Iran) has 60% translated, so this is the main place for Persian translation.

However we can keep Persian if we want, but in that case would be good to rename it to "fa" instead of "fa_AF"

**Comment by MartijnKaijser** [comment]
I'm fine with dropping the 8% translated and get it done proper

**Comment by MartijnKaijser** [comment]
Why are those not available? Are those simply not "official" ISO codes or are they just missing from Transifex?

**Comment by alanwww1** [comment]
> Why are those not available? Are those simply not "official" ISO codes or are they just missing from Transifex?

I have no idea, certainly not available at Transifex. Probably there is a reason to it.
Here are the available codes:
https://www.transifex.com/languages/

I can try to get the Transifex guys to introduce these languages.

**Comment by alanwww1** [comment]
I contacted the Transifex guys and they were really friendly and helpful about this. They already added this 3 new language code to their system. It will go live soon (probably this week), so I am closing this PR as we don't have to change these codes at all.

**Pull request closed without merging**
