### PR TITLE
Import controller add-ons at v1.0.5

### PR DESCRIPTION
**Pull request by garbear**
This imports the controller add-ons from the kodi-game-controllers repo. These controllers are compatible with Kodi pending the merge of https://github.com/xbmc/xbmc/pull/12884.

### CODE REVIEW

**Comment by garbear** [comment]
@MartijnKaijser OK to merge when https://github.com/xbmc/xbmc/pull/12884 is merged?

**Comment by MartijnKaijser** [comment]
Sure

**Comment by garbear** [comment]
The PR is merged. Your button.

**Comment by garbear** [comment]
when do these go live on the add-on server so I can test in the GUI?

**Comment by MartijnKaijser** [comment]
Hours ago. Hot refresh on your repo

**Comment by garbear** [comment]
Stop kicking so much ass

**Comment by MartijnKaijser** [comment]
Gotta love automation till perfection ;)

**Pull request merged**
