### PR TITLE
Sync game controllers

### PR DESCRIPTION
**Pull request by garbear**
### Description

This brings in the latest versions from https://github.com/kodi-game/controller-topology-project.

It brings the default, keyboard and mouse controllers in line with the xbmc repo syncs:

* Nexus - https://github.com/xbmc/xbmc/pull/24636
* Omega - https://github.com/xbmc/xbmc/pull/24635

I think a good time to merge this will be when 20.4 hits 100% deployment on the google play store.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Review by gade01 — APPROVED** [review]

**Comment by garbear** [comment]
Ready to merge.

**Comment by garbear** [comment]
Updated controllers after tagging v1.0.0 (https://github.com/kodi-game/controller-topology-project/pull/304).

Includes changes from:

* https://github.com/kodi-game/controller-topology-project/issues/303.

Not included is the game.controller.keyboard update to v1.1.43 (https://github.com/xbmc/xbmc/pull/25110). I'll PR that once v21.1 is released.

@gade01 Can you merge?

**Comment by garbear** [comment]
Updated with some Russian strings. A few strings are still trickling in from the changes over the last 6 months, but most updates are in and it's a good time to cut a v1.0.0 release.

**Comment by gade01** [comment]
@garbear Thanks, looks good. I'll merge right away.

**Pull request merged**
