### PR TITLE
Include changes missed by the last controller add-ons sync

### PR DESCRIPTION
**Pull request by garbear**
Sorry, this one got left out. Luckily montellese caught it

https://github.com/kodi-game/kodi-game-controllers/compare/f37b130...b95f265

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
You'll need to bump the addon version else it won't update

**Comment by Montellese** [comment]
Sorry I didn't know that these changes already made it into the actual repository so I didn't bump the versions.

**Comment by MartijnKaijser** [comment]
@garbear nudge ;)

**Comment by garbear** [comment]
Leaving on a week long backpacking trip now. I'll take care of this when I return, incredibly low prio, this only changes the order of two buttons

**Pull request closed without merging**
