### PR TITLE
Sync controllers with controller-topology-project

### PR DESCRIPTION
**Pull request by garbear**
## Description

Adds the following controllers:

  * game.controller.amiga.cd32

Also updates translations for various other controllers.

## Screenshots

New Amiga CD32 controller:

Screenshot from 2021-11-10 17-21-34

Mapping Amiga CD32 controller:

Screenshot from 2021-11-10 17-21-57

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by gade01** [comment]
@garbear Should we wait merging until Weblate has finished creating all languages for Amiga CD32 controller?

**Comment by garbear** [comment]
Good idea

**Comment by garbear** [comment]
@gade01 Language files updated

**Review by gade01 — APPROVED** [review]
Looks good to me.
@ronie Good to go?

**Comment by garbear** [comment]
Ping @ronie, looks good?

**Comment by garbear** [comment]
https://github.com/xbmc/xbmc/pull/20505 is in, time to merge?

**Comment by garbear** [comment]
hold on that, I need to check something

**Comment by garbear** [comment]
The "something" wasn't a blocker. There was a language update for controllers so I synced all the changes, all the more reason to merge.

**Comment by razzeee** [comment]
LGTM, I guess the commit message not being in our usual format is unavoidable here.

**Pull request merged**
