### PR TITLE
Remove game.controller default (distributed with Kodi)

### PR DESCRIPTION
**Pull request by garbear**
Should we have game.controller.default in this repo if it's distributed with Kodi?

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Do controllers work when there's no default installed?

**Comment by garbear** [comment]
no. but it's distributed with kodi, so that shouldn't ever be the case

**Comment by MartijnKaijser** [comment]
Right. Mixed up PR location :) 
BTW this version is higher than shipped with Kodi. Might want to update that

**Comment by garbear** [comment]
hm, ran a diff between this and master, and the only difference is the version. looks like I bumped the version here to match the other controllers even though there were no changes.

As a result, master would update from 1.0.0 to 1.0.3 on every startup, but there was no difference, so it was jsut a waste of bandwidth :)

should we bump master to 1.0.3?

**Comment by MartijnKaijser** [comment]
Yes it needs to be bumped higher than repo version else any change in kodi master will never be picked up for people already having this version

**Comment by garbear** [comment]
OK, will PR

**Pull request merged**
