### PR TITLE
[resource.language.gl_es] 9.0.14

### PR DESCRIPTION
**Pull request by naciohr**
### Description
Corrected general locale from "et" to "es".
Added region Vigo, Galiza.
Updated plugin version.

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by naciohr** [comment]
Excuse me, is this pending of another verification or just waiting for a suitable moment to apply the changes?

Thank you.

**Comment by ronie** [comment]
@basrieter @Klojum @DaVukovic 

is this ok, and can/should such changes be done through Transifex?

**Comment by ronie** [comment]
^ @alanwww1

**Comment by naciohr** [comment]
Hello,

I wouls like to have some feedback omnthis and whether further actions are needed.

Thanks.

**Comment by naciohr** [comment]
Hello,

I would like to know whether there is something pending on my side in order to commit these changes.

Thanks and regards.

**Review by gade01 — APPROVED** [review]

**Comment by gade01** [comment]
Looks good to me.
Transifex doesn't update langinfo.xml files.

**Comment by basrieter** [comment]
Ping @alanwww1

**Comment by gade01** [comment]
@naciohr If you're still interested, can you PR matrix branch instead?
And please leave out the version bump.

**Comment by ronie** [comment]
closing this one, as stated, a PR to the matrix branch would be welcome!

**Pull request closed without merging**
