### PR TITLE
[resource.images.languageflags.rounded] 0.0.1

### PR DESCRIPTION
**Pull request by mistervee**
### Description
Rounded coloured language flags. Icons by neurosis13.

From this thread
https://forum.kodi.tv/showthread.php?tid=157923

Permission from neurosis13 to upload to repo from PM.
https://imgur.com/0jNQjEF

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by mistervee** [comment]
Not sure why it failed checks.

**Comment by Rechi** [comment]
rebase on top of the PR base branch, https://github.com/xbmc/repo-resources/commit/f62ddf9 should fix the ci issue

**Comment by Rechi** [comment]
> Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Please rebase your branch on top of the PR base branch (instead of merging) to get rid of the additional merge commit.

**Comment by mistervee** [comment]
I am having some trouble with the github command line.
Still learning. Not sure how to fix it now. I will leave this PR for now until the other two are pushed to the repo.

**Pull request closed without merging**
