### PR TITLE
[resource.images.languageflags.rounded] 0.0.1

### PR DESCRIPTION
**Pull request by mistervee**
### Description
Rounded coloured language flags. Icons by neurosis13.

From this thread
https://forum.kodi.tv/showthread.php?tid=157923

Permission from neurosis13 to upload to repo from PM.
https://imgur.com/0jNQjEF

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by ronie** [comment]
looking good, thx!

**Comment by mistervee** [comment]
@ronie 

Just noticed the colors of the images are different in the xbt. In kodi they all have a shade of blue.

This looks ok;
https://github.com/xbmc/repo-resources/blob/leia/resource.images.languageflags.rounded/resources/UK.png

Extracted from the xbt file


In the skin

**Comment by ronie** [comment]
i've seen those artifacts before... our TexturePacker can be pretty picky about image formats.
if you convert the images indexed colors to RGB, it'll most likely produce better results.

**Comment by mistervee** [comment]
Thanks @ronie,

Converted the bit depth to 32 bit and all is ok. Just submitted a pull request. Tried the kodi texture packer on my local machine and all looks good.

**Pull request merged**
