### PR TITLE
New Controllers

### PR DESCRIPTION
**Pull request by garbear**
This PR contains the new and updated controllers in https://github.com/kodi-game/kodi-game-controllers/pull/9

### CODE REVIEW

**Comment by enen92** [comment]
If I am allowed to add something and just for your information and awareness we have a rule for repository submissions regarding the addon icon - they should have a 100% solid background. See here: http://kodi.wiki/view/Add-on_structure#icon.png . I think the reasoning is to have consistency across skins. I have no ideia if this is also applied to any other addons (controllers in this case) but in any case I leave here the remark :)
Thanks for your awesome work in retroplayer

**Comment by garbear** [comment]
I guess the same applies to fanart too. I didn't include any, but I tried to get tricky and reuse the extra layouts as fanart. This happened:

screenshot000

I'll go through and add opaque backgrounds to the images. What color should I use? And I guess I'll just not include the extra layouts as fanart.

**Comment by Razzeee** [comment]
Part of the reasoning for `icon.png` is that notifications will look like crap if you don't give it a solid background :)

**Comment by garbear** [comment]
Icons have been updated with an opaque background:

icon

**Comment by garbear** [comment]
@MartijnKaijser #12556 is in, OK to merge?

**Comment by garbear** [comment]
Hold off on merging, player manager requires a minor change

**Comment by garbear** [comment]
Superseded by https://github.com/xbmc/repo-resources/pull/33

**Comment by Razzeee** [comment]
Then I'm closing this.

**Pull request closed without merging**
